---
# file: roles/glassfish/tasks/main.yml
- name: install postgres client
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - postgresql-client-common
    - postgresql-client-9.1


- name:  Download Glassfish and war
  get_url: url={{ item.url }} dest={{ item.dest }} owner=ubuntu
  with_items:
     - { url: 'http://download.java.net/glassfish/3.1.2.2/release/glassfish-3.1.2.2-unix.sh', dest: '~ubuntu' }
     - { url: 'http://wrench.res.oicr.on.ca/artifactory/simple/seqware-release/com/github/seqware/seqware-admin-webservice/1.0.14/seqware-admin-webservice-1.0.14.war', dest: '~ubuntu' }

- name: Install Glassfish 
  sudo: yes
  sudo_user: ubuntu
  command: creates=~ubuntu/glassfish3 sh glassfish-3.1.2.2-unix.sh  -s
  
- name:  Download postgres jar
  get_url: url={{ item.url }} dest={{ item.dest }} 
  with_items:
     - { url: 'http://jdbc.postgresql.org/download/postgresql-9.1-903.jdbc4.jar', dest: '~ubuntu/glassfish3/glassfish/domains/domain1/lib' }
  
- name: Change glassfish port
  lineinfile: 
    dest: ~ubuntu/glassfish3/glassfish/domains/domain1/config/domain.xml
    create: no
    regexp: '<network-listener port="8080" protocol="http-listener-1" transport="tcp" name="http-listener-1" thread-pool="http-thread-pool"></network-listener>'
    line: '<network-listener port="38080" protocol="http-listener-1" transport="tcp" name="http-listener-1" thread-pool="http-thread-pool"></network-listener>'
    state: present
  
- name: Start glassfish domain 
  sudo: yes
  sudo_user: ubuntu
  register: domain_start
  command: chdir=~ubuntu/glassfish3/bin/ nohup ./asadmin start-domain
  changed_when: "'There is a process already using the admin port 4848' not in domain_start.stdout"
  ignore_errors: yes

- name: Template glassfish-resources
  template: src=glassfish-resources.j2 dest=~ubuntu/glassfish-resources.xml
  register: resource_template

- name: Delete jdbc resource (if it exists already) 
  sudo: yes
  sudo_user: ubuntu
  command: chdir=~ubuntu/glassfish3/bin/ ./asadmin delete-jdbc-connection-pool --cascade true post-gre-sql_test_seqware_meta_db_seqwarePool
  when: resource_template.changed

- name: Deploy jdbc resource  
  sudo: yes
  sudo_user: ubuntu
  command: chdir=~ubuntu/glassfish3/bin/ ./asadmin add-resources ~ubuntu/glassfish-resources.xml
  when: resource_template.changed

- name: Deploy app  
  sudo: yes
  sudo_user: ubuntu
  command: chdir=~ubuntu/glassfish3/bin/ ./asadmin deploy --name seqware-admin-webservice --contextroot seqware-admin-webservice ~/seqware-admin-webservice-1.0.14.war 