---
# file: roles/glassfish/tasks/main.yml


- name: install postgres client
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - postgresql-client-common
    - postgresql-client-9.1


- name:  Download Glassfish, war, and sample database
  get_url: url={{ item.url }} dest={{ item.dest }} owner=ubuntu
  with_items:
     - { url: 'http://download.java.net/glassfish/3.1.2.2/release/glassfish-3.1.2.2-unix.sh', dest: '~ubuntu' }
     - { url: 'http://wrench.res.oicr.on.ca/artifactory/simple/seqware-release/com/github/seqware/seqware-admin-webservice/1.0.14/seqware-admin-webservice-1.0.14.war', dest: '~ubuntu' }
     - { url: 'https://github.com/SeqWare/seqware/raw/develop/seqware-meta-db/src/main/resources/net/sourceforge/seqware/metadb/util/seqware_meta_db.sql', dest: '~ubuntu' }
     - { url: 'https://github.com/SeqWare/seqware/raw/develop/seqware-meta-db/src/main/resources/net/sourceforge/seqware/metadb/util/seqware_meta_db_data.sql', dest: '~ubuntu' }
     - { url: 'https://github.com/SeqWare/seqware/raw/develop/seqware-meta-db/src/main/resources/net/sourceforge/seqware/metadb/util/seqware_meta_db_testdata.sql', dest: '~ubuntu' }

# need to figure out how to refactor this cleanly
- name:  Register  database relations
  shell: PGPASSWORD=seqware psql -h dbserver -U seqware seqware_meta_db  --command "\dt"
  register: database_state
  changed_when: False

# will need to parameterize this if we ever want the webservice to be on a different host
- name: create database for users
  when: "database_state.stdout.find('No relations found.') != -1"
  shell: $item
  with_items: 
    - PGPASSWORD=seqware psql -h dbserver -U seqware -f ~ubuntu/seqware_meta_db.sql  seqware_meta_db
    - PGPASSWORD=seqware psql -h dbserver -U seqware -f ~ubuntu/seqware_meta_db_data.sql  seqware_meta_db
    - PGPASSWORD=seqware psql -h dbserver -U seqware -f ~ubuntu/seqware_meta_db_testdata.sql  seqware_meta_db

- name: Install Glassfish 
  sudo: yes
  sudo_user: ubuntu
  command: creates=~ubuntu/glassfish3 sh glassfish-3.1.2.2-unix.sh  -s
  
- name:  Download postgres jar
  get_url: url={{ item.url }} dest={{ item.dest }} 
  with_items:
     - { url: 'http://jdbc.postgresql.org/download/postgresql-9.1-903.jdbc4.jar', dest: '~ubuntu/glassfish3/glassfish/domains/domain1/lib' }
  
- name: Change glassfish port
  lineinfile: 
    dest: ~ubuntu/glassfish3/glassfish/domains/domain1/config/domain.xml
    create: no
    regexp: '<network-listener port="8080" protocol="http-listener-1" transport="tcp" name="http-listener-1" thread-pool="http-thread-pool"></network-listener>'
    line: '<network-listener port="38080" protocol="http-listener-1" transport="tcp" name="http-listener-1" thread-pool="http-thread-pool"></network-listener>'
    state: present
  
- name: Start glassfish domain 
  sudo: yes
  sudo_user: ubuntu
  register: domain_start
  command: chdir=~ubuntu/glassfish3/bin/ nohup ./asadmin start-domain
  changed_when: "'There is a process already using the admin port 4848' not in domain_start.stdout"
  ignore_errors: yes
  
- name: Create directory for seqware-admin-webservice
  file: owner=ubuntu state=directory dest=~ubuntu/seqware-admin-webservice 
  
- name: Expand seqware-admin-webservice
  sudo: yes
  sudo_user: ubuntu
  command: creates=~ubuntu/seqware-admin-webservice/cc.gif chdir=~ubuntu/seqware-admin-webservice jar -xvf ../seqware-admin-webservice-1.0.14.war

- name: Template glassfish-resources
  template: src=glassfish-resources.j2 dest=~ubuntu/seqware-admin-webservice/WEB-INF/glassfish-resources.xml
  
- name: Change test-services url
  lineinfile: 
    dest: ~ubuntu/seqware-admin-webservice/test-services.html
    create: no
    regexp: 'var baseURL = "http://localhost:38080/seqware-admin-webservice/\|\|ServletAdaptor\|\|/webresources/\*";'
    line: 'var baseURL = "http://{{ ansible_ssh_host }}:38080/seqware-admin-webservice/||ServletAdaptor||/webresources/*";'
    state: present

- name: Deploy app  
  sudo: yes
  sudo_user: ubuntu
  command: chdir=~ubuntu/glassfish3/bin/ ./asadmin deploy --force --name seqware-admin-webservice --contextroot seqware-admin-webservice ~/seqware-admin-webservice 