---
# file: roles/seqware-code/tasks/main.yml

- name:  Set up SeqWare working directories
  file: path={{ item.path }} state={{ item.state }} owner={{ item.owner }} mode={{ item.mode}} group={{ item.group }}
  with_items:
     - { state: 'directory', path: '~seqware/bin', owner: 'seqware', group: 'seqware', mode: '0700' }
     - { state: 'directory', path: '~seqware/jars', owner: 'seqware', group: 'seqware', mode: '0700' }
     - { state: 'directory', path: '~seqware/crons', owner: 'seqware', group: 'seqware', mode: '0700' }
     - { state: 'directory', path: '~seqware/logs', owner: 'seqware', group: 'seqware', mode: '0700' }
     - { state: 'directory', path: '~seqware/released-bundles', owner: 'seqware', group: 'seqware', mode: '0700' }
     - { state: 'directory', path: '~seqware/provisioned-bundles', owner: 'seqware', group: 'seqware', mode: '0700' }
     - { state: 'directory', path: '~seqware/workflow-dev', owner: 'seqware', group: 'seqware', mode: '0700' }
     - { state: 'directory', path: '~seqware/.seqware/self-installs', owner: 'seqware', group: 'seqware', mode: '0700' }
     - { state: 'directory', path: '~seqware/gitroot/seqware', owner: 'seqware', group: 'seqware', mode: '0700' }
     - { state: 'directory', path: '~seqware/.m2/', owner: 'seqware', group: 'seqware', mode: '0700' }    
     
- name: Check state of HDFS User Directories
  command: hadoop fs -ls /user/seqware
  register: hdfs_user_dir
  changed_when: false
  ignore_errors: yes

  #hmmm, no module for hadoop file operations
- name:  Setup HDFS User Directories
  sudo: yes
  sudo_user: hdfs
  command: $item
  ignore_errors: yes
  with_items: 
    - hadoop fs -mkdir -p /user/seqware
    - hadoop fs -chown -R seqware /user/seqware
  when: "'No such file or directory' in hdfs_user_dir.stdout"
    
- name:  Template seqware settings
  template: src=settings.j2 dest=~seqware/.seqware/settings mode=0640 owner=seqware
  
- name:  Template maven mirror if defined
  template: src=m2_settings.j2 dest=~seqware/.m2/settings.xml mode=0640 owner=seqware
  when: m2_mirror_url is defined
  
# I'm still checking out since I will need the SQL schema file for example
- name: SeqWare - Code - Git | Cloning seqware
  sudo: yes
  sudo_user: seqware
  git: update=no repo=https://github.com/SeqWare/seqware.git dest=~seqware/gitroot/seqware version={{ seqware_repo_version }}

# setup bash profile for seqware
- name:  Bash profile
  lineinfile: 
    dest: ~seqware/.bash_profile
    create: yes
    line: 'export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=512m"'
    state: present
    insertafter: EOF
    owner: seqware
    
- include: 'git.yml'
  when: seqware_provider == "git"

- include: 'artifactory.yml'
  when: seqware_provider == "artifactory"
  
- name:  Setup script path in bash profile
  lineinfile: 
    dest: ~seqware/.bash_profile
    create: yes
    line: 'export PATH=$PATH:~seqware/bin'
    state: present
    insertafter: EOF