--- 
# file: seqware-install.yml
# This file is used for installing a seqware cluster
   
# Not sure why, but I needed this to create a /etc/hosts that actually works with the Ubuntu image here on openstack
- hosts: all
  sudo: True
  # Idempotent way to build a /etc/hosts file with Ansible using your Ansible hosts inventory for a source.
  # Will include all hosts the playbook is run on.
  # Inspired from http://xmeblog.blogspot.com/2013/06/ansible-dynamicaly-update-etchosts.html
  tasks:
  - name: Build hosts file for all hosts
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: groups['all']
  - name: Setting hostname to {{ inventory_hostname }}
    hostname: name={{ inventory_hostname }}

# The grid master depends on the hosts file, as we need to know at least who we
# are by this stage. 
- hosts: master 
  sudo: True
  roles:
    - { role: java, java_provider: Cloudera }
    - { role: grid-engine, grid_engine_master: True }
    - { role: seqware-master-infrastructure }
    - { role: seqware-code }
    - { role: seqware-webservice }

- hosts: worker 
  sudo: True
  roles:
    - { role: java, java_provider: Cloudera }
    - { role: grid-engine, grid_engine_master: False }
    - { role: seqware-worker-infrastructure }
    
- hosts: master 
  sudo: yes
  sudo_user: seqware
  vars: 
      run_integration_tests: false
  roles:
    - { role: seqware-integration-tests, when: "{{ run_integration_tests }} == True" }
    
- hosts: master
  sudo: True
  roles:
    - { role: seqware-cron }
    - { role: seqware-helloworld }
    
# setup the vagrant user as well (for virtualbox mostly) 
- hosts: master 
  sudo: True
  roles:
    - { role: seqware-code, user_name: vagrant }
    - { role: seqware-cron, user_name: vagrant }
